### ISSUE TITLE
[Feature Request] Import path relative to project root

### ISSUE THREAD

**Issue by lonix1** [malvahq/vscode-plugin-dartsass#12]
*Firstly, nice extension... well done!*

If I need to import a file from `node_modules`, then I must do this:

````scss
@import "../../../../../node_modules/bootstrap/scss/_functions.scss";
````

This breaks easily, and is hard to maintain. It's a pain to correctly set this up for every scss file.

It would be MUCH better to use a path **relative to the project root**, e.g.

````scss
@import "node_modules/bootstrap/scss/_functions.scss";
````

or

````scss
@import "~/node_modules/bootstrap/scss/_functions.scss";
````

**Comment by akkumar** [comment]
@lonix1  - by default - node_modules directory is included in the smart importer as used by this plugin. 

So - can you try - 

`
@import "~bootstrap/scss/_functions.scss";
`

Let me know if that does work.

**Comment by lonix1** [comment]
Yes that works, thanks!

It's a nice feature, maybe it should be in the docs.

**Comment by akkumar** [comment]
So - in the README - it sort of exists - https://github.com/malvahq/vscode-plugin-dartsass#smart-imports . 

I understand may be - it should be more prominent. Let me revisit the same.

Of course, meanwhile any suggestions welcome.

**Comment by lonix1** [comment]
Yes you are right, the docs already cover that use case!

**Comment by akkumar** [comment]
Update: since v0.1.0 , the option " ~ " prefix for import statements as described above has been removed altogether.  And any so-called "smart imports" have been removed from the plugin as well. 

It is suggested to do the following instead: 

1) Update `@import "bootstrap/scss/_functions.scss";`  ( note the missing ~ suffix ) .
2) Update `dartsass.includePath: ["node_modules"]` property mentioning the `node_modules' in the list of values under the "Workspace" tab in settings.

This makes it more compatible with the cmd line sass compiler when it comes to generating minified files later on in the dev cycle.

**Comment by lonix1** [comment]
As mentioned in the other issue, this stopped working for me.

e.g. `@import "bootstrap/scss/_functions";`
instead of `@import "../../../../../node_modules/bootstrap/scss/_functions";`

I was wondering, does this still work for you? ...If so then it's just me.

**Comment by akkumar** [comment]
@lonix1 - this must be fixed now. See #22 for more details where it is tracked.
