### ISSUE TITLE
[Question] Relative path for sass binary

### ISSUE THREAD

**Issue by lonix1** [malvahq/vscode-plugin-dartsass#14]
I installed `node-sass` in my project. Then I set `"dartsass.sassBinPath": "node_modules/node-sass/bin/node-sass"`.

But it complains that the binary is not found.

Can this be done without using an absolute path?

**Comment by akkumar** [comment]
Well - this uses the sass package (https://www.npmjs.com/package/sass) behind the scenes and not node-sass. 

In fact one of the motivations for this plugin is to have a pure platform independent sass compiler (so switching between - say a debian-based host and an alpine container does not cause much issues because sass is completely native javascript unlike node-sass).

Having said that - it would be useful to have a relative lookup for sass binary though. let me look into the same.

**Comment by lonix1** [comment]
The reason I installed it is only to use the "watch" feature (which complains that I must install sass). I don't mind which one is used.

Using a relative path would be best though.

(However what I don't get is why the watch feature doesn't work with the sass compiler integrated into the extension?)

**Comment by akkumar** [comment]
So a new version `0.0.86` has been released that takes the sassBinPath as a relative path  ( in addition to the previous absolute path as well ). 

sassBinPath is relative to the current project in the workspace ( identified by the current file, being edited by the active editor ).

> BTW why doesn't the watch feature work with the sass compiler integrated into the extension?

Well - the watch directory option is present in the sass executable as a cmd line argument. 

But I could not find it in the sass JS/typescript API that the compilation of sass compilation rely on. Hence the need to specify an external PATH while watching directories.

**Comment by lonix1** [comment]
Wow so quick, you are a machine! 😄 

Please tell me if I'm doing it correctly. I want to use the "watch" feature so that if I save a dependent file it will also automatically update the dependee files.

- Suppose `file3.scss` imports `file2.scss` which imports `file1.scss`, etc....
- I installed `node-sass` and set `"dartsass.sassBinPath": "node_modules/node-sass/bin/node-sass"`
- (I also tried `sass` and set `"dartsass.sassBinPath": "node_modules/sass/sass.js"`)
- I right-clicked my `css` directory and chose `DartSass: Sass Watch`
- I updated file1, and saved

Then I get an error
>An output directory must be specified when compiling a directory

I assume this is related to the `dartsass.targetDirectory` option? I didn't set it because I want it to save the ".css" files in the same directory as the ".scss" files.

What did I do wrong?

**Comment by akkumar** [comment]
So - I would assume the following issue

1) dartsass.sassBinPath must be set to `node_modules/.bin/sass`  ( it should point to the `sass` binary). 

Of course, please try `sass` and not `node-sass`, as the cmd-line args are written for sass and not for node-sass.

**Comment by lonix1** [comment]
For `node-sass` the executable seems to be `node-sass`. But I'm gonna use `sass` as you recommend.

But it doesn't seem to work.

Without watching:
- I leave `dartsass.sassBinPath` empty
- I update `_parent.scss` and save
- I must manually save `child.scss`
- ...so it's not automated, but everything works

With watching:
- I use `"dartsass.sassBinPath": "node_modules/sass/sass.js"`
- I update `_parent.scss` and save
- BUT `child.scss` is not automatically updated, and there's no output in "DartJS Sass" log window
- As a test, I manually save `child.scss` but then the log window shows "Error: Can't find stylesheet to import" (for a number of files imported in `_parent.scss`)

So the imports work UNTIL I use the external sass compiler `"dartsass.sassBinPath": "node_modules/sass/sass.js"`.

*Sorry for troubling you, it's probably just my setup, rather than an issue* 😢

**Comment by akkumar** [comment]
Can you help try with the property: 

"dartsass.sassBinPath": "node_modules/.bin/sass"

That is what I had tested with before releasing this extension.

**Comment by akkumar** [comment]
Ok - On re-reading your comment above - 

>  As a test, I manually save child.scss but then the log window shows "Error: Can't find stylesheet to import" (for a number of files imported in _parent.scss)

So - the fact that this error came out on the vsce console indicates that the sassbinPath did work correctly and hence, the sass compiler was invoked. 

It seems the error has to do with the includePath of sass compiler , may be ? Are `_parent.scss` and `child.scss` in the same directory though ? 

If not - you can have a look at the `includePath` option of this vscode plugin to specify directories to look for files for compilation. 

> BUT child.scss is not automatically updated, and there's no output in "DartJS Sass" log window

As it stands today - there is no output in the log window for positive compilation (with automatic compilation for every save, that would be too many ! ). An output appears only in case an error happens for compilation. 

Can you invoke the command:  `> DartSass: View Sass watchers`.

This should list all the processes being watched in the "DartJS Sass" window in output. If your directory appears there - indeed the watcher was working. Otherwise no. 

From the information - it seems more an issue of `includePath` not being set correctly to include all directories containing the `_` files, as opposed to an issue with `sassBinPath`. 

If you make any headway feel free to share. would love to help and see this working !

**Comment by akkumar** [comment]
So I did examine the code and has pushed a bugfix where the `includePath` were being ignored when `watched` by the sass compiler.  They were taken into account when a single file was being compiled though. 

Can you help update the version (0.0.87 contains the fix) and see if that fixes your problem as it seems more related to includePath rather than sassBinPath . 

Let me know how that goes.

**Comment by akkumar** [comment]
So I had cut another release v0.0.88 . 

When I watch a directory - in the log under `DartJS Sass` - I see the following. 
`
Watching /opt/code/src/hello/input. Exec /opt/code/src/hello/node_modules/.bin/sass --style  compressed  --no-source-map  --watch  /opt/code/src/hello/input:/opt/code/src/hello/out
`

My workspace specific sassBinPath reads as:

`dartsass:sassBinPath: node_modules/.bin/sass`

The options - "targetDirectory" and "targetMinifiedDirectory" are completely optional and not mandatory ( though I had set `"targetDirectory" : "out"` in my case )

So please go ahead and update the extension and apply the settings as mentioned above and let me know what you see in the logs so we can debug the same.

**Comment by lonix1** [comment]
Sorry only saw this now. Couple of things:

- The files `_parent.scss` and `child.scss` are in the same directory, so I don't think it's a `includePath` problem.
- I'm using `sass` as you recommended. The path `node_modules/.bin/sass` just points to `node_modules/sass/sass.js`, but I'm doing it your way just to be sure.

I have in the same directory:

_parent.scss
````scss
// bootstrap stuff
@import "~bootstrap/scss/_functions.scss";
@import "~bootstrap/scss/_variables.scss";
@import "~bootstrap/scss/mixins/_breakpoints.scss";
// other stuff
@import "_foo.scss";
@import "_bar.scss";
```` 

child.scss
````scss
// imports
@import "./_parent.scss";
// other stuff...
````

When I don't specify `dartsass:sassBinPath` then I can't use watching, and I have to save everything manually, but it works.

When I use `"dartsass:sassBinPath": "node_modules/.bin/sass"` then when I save `child.scss` the log window shows
>Error: Error: Can't find stylesheet to import.
   ╷
1 │ @import "~bootstrap/scss/_functions.scss";
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  myproject/src/css/_parent.scss 13:9   @import
  myproject/src/css/child.scss 13:9  root stylesheet

So it's not working at all. But the paths and syntax are correct, because it works with the built-in sass compiler.

I'm starting to think that maybe this is a weird local problem and that there's nothing wrong with the extension and that I'm wasting your time. 😭  If you see something obviously wrong please tell me, otherwise please don't worry about it! Maybe we can wait to see if anyone else has this problem as well so we can determine if it's just me or not.

**Comment by akkumar** [comment]
Thanks for the detailed steps of reproduction. 

I think what is happening is the following: 

1) sass directory watcher does not use any special importer as such to recognize the "~" in the import.  So - `sassBinPath` ( and no issue with `includePath` as you had mentioned since they are in the same directory after all) seems to work. 

2) On an individual file basis though, the built-in sass package uses the `node-sass-package-importer` (separate from the cmd line version using `sassBinPath` ) in the api calls and hence the "~" prefix works with import statements. 

So - the core issue seems to be fact that the watch directory option (that uses the cmd line option) does not seem to use "~" prefix operator ( in turn not using the node-sass-package-importer ).  I am going to log a separate issue to track that. 

Meanwhile - you can try the following

change the import statement to:

> @import "bootstrap/scss/_functions.scss"

(Note the lack of "~" character in the beginning of the import path). 

Also modify the `includePaths` in workspace settings for DartSass plugin to add - "node_modules" directory of the current project. 

This will make sure the sass watch happens without an error .

Let me know how this goes and feel free to paste the "Watching <directory> . Exec <cmd> " that you see in the logs if there is an issue.

**Comment by akkumar** [comment]
> So it's not working at all. But the paths and syntax are correct, because it works with the built-in sass compiler.
I'm starting to think that maybe this is a weird local problem and that there's nothing wrong with the extension and that I'm wasting your time.

Well - thanks for your time to report the issue in detail.

The more I read about this issue, the more I think the non-standard "~" prefix causes more trouble than it is worth. 

Even if somehow I make the sass watch directory respect the "~" prefix, ( I am not sure how but keeping that aside...) , the "~" prefix may not be compatible with the sass binary that might be used in one of the npm scripts to pack the sources together. 

So I am seriously thinking of removing the "~" prefix support altogether (and any dependency on 'node-sass-package-importer' and just recommending to use "node_modules" directory as an `includePath` to identify the libraries. That seems more compatible with the cmd line option as well. 

Let me know if you are able to make this work and then your thoughts on the removing the support of "~" altogether.

**Comment by lonix1** [comment]
**Your ideas worked!!**

Yes I agree with you - it's better to keep it simple. So the docs can say that if you want to include node modules, then you must use:
````json
"dartsass.includePath": ["node_modules"]    // assumes node_modules is in project root
````

Also it's good to recommend to use `sass` instead of `node-sass`, since we know the former works properly. And we must use:

````json
"dartsass.sassBinPath": "node_modules/.bin/sass"
````

Thanks for all your help! And let me know if you want to test anything else.

**Comment by lonix1** [comment]
(BTW now that I have got "watching" function working properly - do you know if there is a way to make vscode run it automatically when the project opens? There was a way to do something like that in the `.vscode` config files but I can't remember, it was a while ago and was for a different extension.)

**Comment by akkumar** [comment]
Great @lonix1 . I have released a v0.1.0 version of the plugin that has removed the support of `node-sass-package-importer` altogether.  It would be great if you can test that and let me know how that goes. 

Regarding your feedback , I have added questions to the FAQ here- https://github.com/malvahq/vscode-plugin-dartsass#faq .   Questions 3, 4 and 5 address the issue mentioned above. 

The more I read the FAQ I wish it should be well formatted better. But for now- the information exists though. 

Feel free to suggest improvements as you see fit.

**Comment by akkumar** [comment]
> (BTW now that I have got "watching" function working properly - do you know if there is a way to make vscode run it automatically when the project opens? There was a way to do something like that in the .vscode config files but I can't remember, it was a while ago and was for a different extension.)

So right now - the watchers get killed when vscode stops ( so we don't want any dangling sass watcher processes outside vscode ). 

I don't know a way to persist information that a directory is being watched in a workspace and then the watchers getting started all over again , although i can see why that would be a good idea. Need to explore the vsce api a bit. Pointers if any would be helpful. 

> Thanks for all your help! And let me know if you want me to test anything else.

Always welcome and thanks for your time for me to help understand this bug better. 

Most of the features of the plugin are driven by community so feel free to share more feedback / use cases that you think can make this plugin better. 

Feel free to drop a feedback here at the vsce extension here [malvahq.dartsass](https://marketplace.visualstudio.com/items?itemName=malvahq.dartsass) so others can get to explore this extension better. 

Of course,  'star'-ing in github would also help :)

**Comment by lonix1** [comment]
I added a star! I'll add a star at the marketplace too.
And I like the new docs.
Also I tested the latest version and it works 100%.
👍
