### ISSUE TITLE
[Feature Request] Automatically start watch on vscode start

### ISSUE THREAD

**Issue by lonix1** [malvahq/vscode-plugin-dartsass#15]
As [discussed here](https://github.com/malvahq/vscode-plugin-dartsass/issues/14#issuecomment-568424731) it would be nice if the extension could automatically start watching a directory on vscode start.

I often forget to start watching, then spend time scratching my head wondering why things aren't working 😄

I looked into the extensions API and it looks like there's [a simple hook](https://code.visualstudio.com/api/references/activation-events#Start-up) (an "activation event") that triggers the extension to load on start.

If there is a new item in the options - e.g. `dartsass.autowatchPath` - then the extension could start watching that directory automatically on start. It's kinda hacky to hardcode the path, but it's better than nothing.

Anyone else likes this idea?

**Comment by akkumar** [comment]
The feature definitely seems interesting and useful. 

It would be interesting to check if vsce has an API to persist changes (to the config, say) across sessions. So we can record the list of directories being watched and restart if necessary. 

As regarding "activation events" - we already have that in the version today , that it gets activated when we open a file that is of type .scss .

**Comment by lonix1** [comment]
I think the `"*"` activation event triggers when vscode itself starts up. I'm not sure, but I assume that's the key ingredient here.

As far as persisting the directory/directories to watch, that would be nice, but I assume it would be much more complex.

**Comment by akkumar** [comment]
So a new release (v0.2.1 or later) has been made that will persist watchers across vsce sessions. 

So - if you watch a set of directories and close vsce and then start vsce later, the watcher processes would be spawned again so there would be no need to redo the watching process again. A new property `watchDirectories` added to the plugin that *persists* the directories being watched. There is no need to manually play with the property since the property indeed is modified based on the watch/ unwatch actions from within the IDE.  

> I  think the "*" activation event triggers when vscode itself starts up.

So ( as it was before ) , the activation event gets triggered when we open a scss file or invoke one of the dartsass commands ( "say Sass Version" /  "View Sass Watchers" etc. ) . 

I am slightly reluctant to associate that with "*" since that is a wildcard that matches everything and probably too much of an overhead for the plugin to be activated (say a project that contains no .scss files etc. and this plugin is not very relevant to that project ). 

So , if we want the watchers to be retained after the IDE gets restarted, all we need to do is to open a scss file ( or invoke any other - "DartSass: " commands ) and then the plugin gets 'activated' and then the watcher processes will automatically start running. 

Let me know how this goes and feel free to share feedback if any.

**Comment by lonix1** [comment]
Couldn't get it working initially because I didn't understand that I must first open an scss file to trigger this behavior. But now that I know that it works well.

Awesome new feature.. well done! 😃

**Comment by akkumar** [comment]
Good to know that it works for you. 

>  I didn't understand that I must first open an scss file to trigger this behavior. 

Not just this feature, but rather the entire plugin gets activated only when .scss files are opened or one of the commands - ("DartSass: View Sass Watchers" / "Say Sass Version" etc. ) is invoked. 

And only then the plugin reads previous `watchDirectories` persisted in the folder and spawns sass processes to "watch" those directories. 

Just to clarify a bit more on what happens behind the scenes.

**Comment by lonix1** [comment]
You should know this plugin is great because it lets me work on a project without setting up a complete node / scripts / gulp/grunt / whatever toolchain.

Sometimes you just wanna work on something "small" without all the fluff.

So relying on various vscode plugins to do all that stuff is a major win.

**Comment by akkumar** [comment]
Thanks for thw words. 

Feel free to share the same to help spread the word :) (Link available in README.md ).

Thanks for your time to report the issues. Keep the feedback / improvements coming.

**Comment by lonix1** [comment]
Added review on marketplace! 👍
