### ISSUE TITLE
watch and min files

### ISSUE THREAD

**Issue by lekoala** [malvahq/vscode-plugin-dartsass#17]
As far as I can tell, when using the watch feature, only one file is being updated

example:

if i have a main.scss file, on save behaviour is to create main.css and main.min.css

but with the watch feature, it will only compile main.scss => main.css (and it would be compressed) and not main.min.css. so end result, we have a main.css that is compressed and a main.min that is not updated. 
do we need to have two watchers, one for unminified files, and one for minified files? seems overkill but it would be consistent.

one other way to look at it, is to enable outputting ONLY min files (so main.css would be minified, regardless it's been generated with on save or watcher), and no need for ".min" suffix. in my case it would be great since i don't really need uncompressed css files anyway and it would save some compiling time.

Or maybe always keep ".min" suffix for consistency when minified.

**Comment by akkumar** [comment]
> As far as I can tell, when using the watch feature, only one file is being updated. 

This is the current behavior with the current code as only one watch process is being launched today. 

Ideally 2 separate processes should be launched though - one for minified and unminified. 

>  it will only compile main.scss => main.css (and it would be compressed)   

This definitely seems like a bug. Looking into it.  

> one other way to look at it, is to enable outputting ONLY min files (so main.css would be minified, regardless it's been generated with on save or watcher), and no need for ".min" suffix.

I am slightly biased towards maintaining them separately since it will help debugging ( the normal one for better readability and the minified ones for production deployment ). 

I will roll out a fix soon in the next couple of days as the current behavior is quite confusing as you had pointed out. Thanks for your time to report it.

**Comment by akkumar** [comment]
Version 0.2.6 released that contains this fix. 

Thanks for helping figuring out this crazy bug. 

From now on, 2 sass watcher processes get launched with every `DartSass: Watch Directory` menuitem/command.  The first watcher generates normal css files without being minified and the second watcher generates the minified files as well. More CPU load as well. 

If the flag - `disableMinifiedFileGeneration` is set , then the second watcher process is not launched at all.

Let me know if this helps.

**Comment by akkumar** [comment]
So - made another release v0.2.7 as well. 

In case, `targetMinifiedDirectory` is not specified then the second sass watcher for minified directory is not launched. 

Since this would end up with having 2 watchers with the same destination directory and it causes confusion , the plugin prefer to not launch the minified sass launcher in case `targetMinifiedDirectory` is not specified. FYI .

**Comment by akkumar** [comment]
Yet another bug fix release - v0.2.8 . 

In case of minified files, the sass watcher still uses the prefix .css (as opposed to .min.css which seems more logical) when we specify `targetMinifiedDirectory`.

    Until now, when we edit files in the editor and save, the plugin used to save minified files with a .min.css extension. 

    To synchronize behavior with underlying sass watcher nomenclature, from now on, even in editor when we save files, the minified files are saved as `.css` files only without the `.min` suffix in it. 

    Of course, in case `targetDirectory` and `targetMinifiedDirectory` are the same , then `.min.css` suffix is used so as to not step on/overwrite non-minified files by mistake.

**Comment by lekoala** [comment]
@akkumar I'm impressed as usual by the speed of your response. I wish every issue I encounter were so quickly solved :-)

**Comment by akkumar** [comment]
Nice to hear your feedback on the plugin.

Feel free to share the same to help spread the word :) (Link available in [README.md](https://github.com/malvahq/vscode-plugin-dartsass#share) ). 

Thanks for your time to report the issues. Keep the feedback / improvements coming.

**Comment by akkumar** [comment]
@lekoala - closing this issue for now if everything is working. feel free to reopen the same in case of any other issue.
