### ISSUE TITLE
Do not compile files starting with _

### ISSUE THREAD

**Issue by lekoala** [malvahq/vscode-plugin-dartsass#2]
Would it be possible to prevent compilation of files starting with _ ? it's really annoying to have these css files created for nothing. or worse, sometimes it's not even working because of missing imports.

**Comment by akkumar** [comment]
Newer plugin release 0.0.62 should contain the fix for the same. So , files beginning with underscores would not be compiled anymore. 

Just in case, anyone wants to compile files beginning with '_' , the property `enableStartWithUnderscores` can be set to enable compiling files beginning with '_' . By default it is false and hence files beginning with '_' will not be compiled by default. 

@lekoala  - thanks for the feedback.  Let me know if this works.

**Comment by lekoala** [comment]
works great thanks!
