### ISSUE TITLE
Watch dependency file changes

### ISSUE THREAD

**Issue by akkumar** [malvahq/vscode-plugin-dartsass#4]
Per #3, @lekoala commented -

`
would there be a way to watch changes from imported files somehow? i'd love to have my main scss file compiled when i update one of the imports?
`

Tracking this issue separate from #3

**Comment by lekoala** [comment]
as a quick note, i got used to this when using
https://github.com/oklai/koala

but the development of this has stopped and it makes more sense to have something integrated into vscode anyway

basically, i think it works because you add the whole folder and it track changes in all relevant files in this folder
https://github.com/oklai/koala/blob/7f0098ee06f4fd174fb60147bba15bdb156ff50f/src/app/scripts/fileWatcher.js

also maybe it's not worth it to support "imports" but rather "use"
https://sass-lang.com/documentation/at-rules/use

(actually that what got me into your module in the first place since dart sass is the only compiler to support @use )

**Comment by lekoala** [comment]
hey @akkumar maybe it's actually easier that it sounds
https://sass-lang.com/documentation/cli/dart-sass#watch
could it be possible to simply allow the extension to watch a given file?

**Comment by akkumar** [comment]
This definitely seems pretty interesting. I am thinking of adding this feature but will probably be disabled by default, given how much of a cpu hog it might turn out to be. 

Let me look into the best trade-off here.

**Comment by gacallea** [comment]
+1 on watching dependency file changes. at the minute we have to save the dep + shred + main, it's boring.

suggestion: it doesn't need to be a continuous process watching changes. you could use a temporary file/db (like sqlite in /tmp or something) with timestamps of the files; compare timestamps for each single file on saves and act accordingly. just an idea eh, I'm sure there's better than this.

**Comment by akkumar** [comment]
Added the initial support for `watching` herewith. FYI . It needs sassBinPath property to be set for watch to be working though. 

More details below. Important this is in `beta` but comes enabled by default so it assumes the developer knows what they are doing. 

## Menu

### DartSass: Sass Compiler Watch

  In the file explorer on the left hand side, when we right-click on a directory, we get a menuitem `DartSass: Sass Compiler Watch` .
  This option appears only in the case of a directory and not in case of individual files.


  This command `watches` the directory using the option `sass --watch input:output` .

  ```
  Important: For this menu to work, an external sass binary should be set for `sassBinPath` property. Otherwise it will indicate an error.
  ```

  After the directory is successfully watched, an entry is added to the statusbar on the lower right bottom - `Sass Watchers: 1` (or any number as appropriate).

  When the IDE is closed the subprocesses launched for watching get killed automatically.

  To view the list of watched processes / directories, use the command: `DartSass: View Sass Watchers` and then check the `Output` under `DartJS Sass`.

  It will list all the watched source directories and the pid (tested in unix) for those processes.

  ```
  TODO: 1) Right now, there is no way to kill / unwatch the directories from inside the IDE individually one at a time.

  Although all the processes eventually get killed when we close the IDE though.

  2) Also the list of watchers need to be better visualized than the naive output in the console.
  ```

**Comment by lekoala** [comment]
so it looks almost perfect! it seems though it's not generating the minified file alongside that regular css file. its also generating a css map

so maybe have a look at this setting so that it's consistent? either it should generate sourcemap also in the default scenario. maybe a setting should be available like for autoprefixer?
https://sass-lang.com/documentation/cli/dart-sass#source-map-urls

also, does setting the executable in sassBinPath would also be used for the default compilation?
it's probably good that it's the same binary that is used in both scenarios

also, in windows it's opening a window with the output. if i close the window, it stops watch but the extension does not seem to notice that the file watcher is stopped.

**Comment by akkumar** [comment]
@lekoala  - 1) Valid point regarding the inconsistency of source map generation between the defaults and the `sassbinpath` option. Let me look into adding another option to set the defaults and make it consistent. 

2) Yup. If `sassBinPath` is set - it will be used for default compilation as well ( overriding the built-in sass library that comes with the plugin ). The drawback is that - the errors would not appear though in the IDE notification but only in the console output under "DartJS Sass" . 

3) Regarding windows inconsistency, ubuntu user here. So unable to reproduce it. 
But I think I could make a vague guess about why this might be happening since the spawn_process is set with shell to be true. Let me work on a revised release to see if that can be fixed.

**Comment by akkumar** [comment]
Release 0.0.75 contains some of the following fixes.

  * Fix 1: SourceMap is consistently generated , whether used by the built-in sass compiler or by the external compiler `sassBinPath` as well.
  * Fix 2: When watching directories, minified files are also getting generated (unless `disableMinifiedFileGeneration` is set ). If `disableMinifiedFileGeneration` is set - then the watchers need to be unwatched and rewatched again manually for the changes to be effected.
  * Fix 3: No shell launched when sass watcher is launched. Let me know if that fixes the issues with windows.

### DartSass: Sass Unwatch

  In the file explorer on the left hand side, when we right-click on a directory, we get a menuitem `DartSass: Sass UnWatch` .
  This option appears only in the case of a directory and not in case of individual files.

  If a directory was watched before, this kills the process used to watch the directory.

  In case the directory was not watched before, a warning message appears indicating that no watcher exists for that directory.

**Comment by akkumar** [comment]
@lekoala - I have made some changes and fixed some bugs in the watch feature as well. 

For example, if we change the sassBinPath or change the target directory in the configuration, the old watchers are killed and new ones spawned with the revised settings as well ( same source directories as before but different target directory or a different sass compiler as applicable ). 

Let me know if there is anything else you notice. Feel free to add feedback if any.

**Comment by akkumar** [comment]
Closing this issue for now as watch has been implemented and present in the plugin
